logging:
  level:
    root: INFO

amazon:
  associatedId: habuma-20

  
---
  
spring:
  profiles: development
logging:
  level:
    root: DEBUG
    
    
---

spring:
  profiles: production
logging:
  path: /tmp/
  file: BookWorm.log
  level:
    root: WARN
